[package]
name = "yew_form"
version = "0.1.8"
authors = ["J-F Bilodeau <jfbilodeau@chronogears.com>"]
edition = "2018"
description = "Bringing MVC to Yew! A set mildly opinionated Yew component to map and validate a model to a HTML form"
license = "MIT"
repository = "https://github.com/thebearjew/yew_form"
readme = "../README.md"
categories = [ "web-programming" ]

[dependencies]
<<<<<<< HEAD
validator = "0.14.0"
validator_derive = "0.14.0"
yew = "0.18"
=======
wasm-bindgen = "0.2"
validator = "0.14.0"
validator_derive = "0.14.0"
yew = "0.19.3"
gloo-console = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
"HtmlInputElement",
"HtmlSelectElement",
"HtmlTextAreaElement"
]
>>>>>>> fa67514a4897880b89e3e13161797e6877d3f50b
